version: "3.6"
services:
  chainlink-bsc:
    container_name: chainlink-bsc
    image: smartcontract/chainlink:0.10.2
    entrypoint: /bin/sh -c "chainlink node import /run/secrets/keystore && chainlink node start -d -p /run/secrets/node_password -a /run/secrets/apicredentials"
    restart: always
    env_file:
      - postgres.env
      - chainlink-bsc.env
    ports:
      - 6689:6688
    secrets:
      - node_password
      - apicredentials
      - keystore
    depends_on:
      - postgres
    networks:
      - chainlink
    volumes:
      - ./chainlink-bsc:/chainlink
  # chainlink-eth:
  #   container_name: chainlink-eth
  #   image: smartcontract/chainlink:0.10.2
  #   entrypoint: /bin/sh -c "chainlink node import /run/secrets/keystore && chainlink node start -d -p /run/secrets/node_password -a /run/secrets/apicredentials"
  #   restart: always
  #   env_file:
  #     - postgres.env
  #     - chainlink-eth.env
  #   ports:
  #     - 6688:6688
  #   secrets:
  #     - node_password
  #     - apicredentials
  #     - keystore
  #   depends_on:
  #     - postgres
  #   networks:
  #     - chainlink
  #   volumes:
  #     - ./chainlink-eth:/chainlink
  chainlink-heco:
    container_name: chainlink-heco
    image: smartcontract/chainlink:0.10.2
    entrypoint: /bin/sh -c "chainlink node import /run/secrets/keystore && chainlink node start -d -p /run/secrets/node_password -a /run/secrets/apicredentials"
    restart: always
    env_file:
      - postgres.env
      - chainlink-heco.env
    ports:
      - 6688:6688
    secrets:
      - node_password
      - apicredentials
      - keystore
    depends_on:
      - postgres
    networks:
      - chainlink
    volumes:
      - ./chainlink-heco:/chainlink
  postgres:
    image: postgres
    restart: on-failure
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - chainlink
  initiator:
    build: ./initiator
    image: initiator
    container_name: initiator
    restart: on-failure
    env_file:
      - postgres.env
      - initiator/.env
    depends_on:
      - postgres
      - chainlink-heco
      - chainlink-bsc
    networks:
      - chainlink

volumes:
  chainlink:
networks:
  chainlink:
    name: chainlink
secrets:
  node_password:
    file: ./password.txt
  apicredentials:
    file: ./apicredentials
  keystore:
    file: ./secrets/keystore.json
